USE SisRent
GO

INSERT  INTO VehMarcas
        ( IdMarca, Marca )
VALUES  ( 1, 'Abarth' ),
        ( 2, 'Alfa Romeo' ),
        ( 3, 'Aro' ),
        ( 4, 'Asia' ),
        ( 5, 'Asia Motors' ),
        ( 6, 'Aston Martin' ),
        ( 7, 'Audi' ),
        ( 8, 'Austin' ),
        ( 9, 'Auverland' ),
        ( 10, 'Bentley' ),
        ( 11, 'Bertone' ),
        ( 12, 'Bmw' ),
        ( 13, 'Cadillac' ),
        ( 14, 'Chevrolet' ),
        ( 15, 'Chrysler' ),
        ( 16, 'Citroen' ),
        ( 17, 'Corvette' ),
        ( 18, 'Dacia' ),
        ( 19, 'Daewoo' ),
        ( 20, 'Daf' ),
        ( 21, 'Daihatsu' ),
        ( 22, 'Daimler' ),
        ( 23, 'Dodge' ),
        ( 24, 'Ferrari' ),
        ( 25, 'Fiat' ),
        ( 26, 'Ford' ),
        ( 27, 'Galloper' ),
        ( 28, 'Gmc' ),
        ( 29, 'Honda' ),
        ( 30, 'Hummer' ),
        ( 31, 'Hyundai' ),
        ( 32, 'Infiniti' ),
        ( 33, 'Innocenti' ),
        ( 34, 'Isuzu' ),
        ( 35, 'Iveco' ),
        ( 36, 'Iveco-pegaso' ),
        ( 37, 'Jaguar' ),
        ( 38, 'Jeep' ),
        ( 39, 'Kia' ),
        ( 40, 'Lada' ),
        ( 41, 'Lamborghini' ),
        ( 42, 'Lancia' ),
        ( 43, 'Land-rover' ),
        ( 44, 'Ldv' ),
        ( 45, 'Lexus' ),
        ( 46, 'Lotus' ),
        ( 47, 'Mahindra' ),
        ( 48, 'Maserati' ),
        ( 49, 'Maybach' ),
        ( 50, 'Mazda' ),
        ( 51, 'Mercedes-benz' ),
        ( 52, 'Mg' ),
        ( 53, 'Mini' ),
        ( 54, 'Mitsubishi' ),
        ( 55, 'Morgan' ),
        ( 56, 'Nissan' ),
        ( 57, 'Opel' ),
        ( 58, 'Peugeot' ),
        ( 59, 'Pontiac' ),
        ( 60, 'Porsche' ),
        ( 61, 'Renault' ),
        ( 62, 'Rolls-royce' ),
        ( 63, 'Rover' ),
        ( 64, 'Saab' ),
        ( 65, 'Santana' ),
        ( 66, 'Seat' ),
        ( 67, 'Skoda' ),
        ( 68, 'Smart' ),
        ( 69, 'Ssangyong' ),
        ( 70, 'Subaru' ),
        ( 71, 'Suzuki' ),
        ( 72, 'Talbot' ),
        ( 73, 'Tata' ),
        ( 74, 'Toyota' ),
        ( 75, 'Umm' ),
        ( 76, 'Vaz' ),
        ( 77, 'Volkswagen' ),
        ( 78, 'Volvo' ),
        ( 79, 'Wartburg' )
GO
